//
//  MenuScenePresenter.swift
//  Arhimedforce
//
//  Created by User on 03.12.2019.
//  Copyright (c) 2019 User. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenuScenePresentationLogic
{
  func presentSomething(response: MenuScene.Something.Response)
}

class MenuScenePresenter: MenuScenePresentationLogic
{
  weak var viewController: MenuSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MenuScene.Something.Response)
  {
    let viewModel = MenuScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
