//
//  MenuSceneInteractor.swift
//  Arhimedforce
//
//  Created by User on 03.12.2019.
//  Copyright (c) 2019 User. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenuSceneBusinessLogic
{
  func doSomething(request: MenuScene.Something.Request)
}

protocol MenuSceneDataStore
{
  //var name: String { get set }
}

class MenuSceneInteractor: MenuSceneBusinessLogic, MenuSceneDataStore
{
  var presenter: MenuScenePresentationLogic?
  var worker: MenuSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MenuScene.Something.Request)
  {
    worker = MenuSceneWorker()
    worker?.doSomeWork()
    
    let response = MenuScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
