//
//  FirstScenePresenter.swift
//  Arhimedforce
//
//  Created by User on 30.10.2019.
//  Copyright (c) 2019 User. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstScenePresentationLogic
{
  func presentSomething(response: FirstScene.Something.Response)
}

class FirstScenePresenter: FirstScenePresentationLogic
{
  weak var viewController: FirstSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FirstScene.Something.Response)
  {
    let viewModel = FirstScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
