//
//  SecondSceneInteractor.swift
//  Arhimedforce
//
//  Created by User on 30.10.2019.
//  Copyright (c) 2019 User. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondSceneBusinessLogic
{
  func doSomething(request: SecondScene.Something.Request)
}

protocol SecondSceneDataStore
{
  //var name: String { get set }
}

class SecondSceneInteractor: SecondSceneBusinessLogic, SecondSceneDataStore
{
  var presenter: SecondScenePresentationLogic?
  var worker: SecondSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SecondScene.Something.Request)
  {
    worker = SecondSceneWorker()
    worker?.doSomeWork()
    
    let response = SecondScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
