//
//  SecondScenePresenter.swift
//  Arhimedforce
//
//  Created by User on 30.10.2019.
//  Copyright (c) 2019 User. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondScenePresentationLogic
{
  func presentSomething(response: SecondScene.Something.Response)
}

class SecondScenePresenter: SecondScenePresentationLogic
{
  weak var viewController: SecondSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SecondScene.Something.Response)
  {
    let viewModel = SecondScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
